### ISSUE TITLE
Tenes aprobado el TP4 con la nota mínima

### ISSUE THREAD

**Issue by evolentini** [monzonlucasfabricio/cese-testing-tp4#1]
Lucas, el código que esta probando es artificial y como resultado las pruebas son demasiado elementales. Lamentablemente ya no hay margen de corrección, así que tenes el TP4 aprobado con la nota mínima que equivale a un 6 o 7.

**Comment by monzonlucasfabricio** [comment]
Buenos días, gracias por la corrección. El código que utilicé para el TP4
es parte del módulo de recepción del puerto serie. No tiene funcionalidades
por lo tanto es solo recepción del dato que llega y chequeo del comando
completo.

Saludos, buen fin de semana.
Lucas.

**Comment by evolentini** [comment]
Lucas, en ese caso tenes problemas de diseño, si la librería tiene por objetivo analizar los comandos que llegan por el puerto serie entonces debería llamar a las funciones que implementan el comando una ve que lo reconoce e identifica los parámetros. Una de las cosas importantes en un diseño es no asignar demasiadas responsabilidades a una librería, pero asignarle muy pocas es igual de malo. Si la librería ya reconoció el comando lo más natural es que lo "despache" justo después de reconocerlo. No se si queda claro el comentario, si queres me avisas y lo charlamos por un meet.

**Comment by monzonlucasfabricio** [comment]
Esteban, si lo entendí masomenos. Me gustaría charlar en un meet sobre el
tema del diseño. Avisame cuando puedas y hacemos un meet. Muchas gracias.

Saludos,
Lucas.
